_G["Pad"] = {
	["ConfigDefaultAssigns"] = loadstring()
	CalculateStickDirection()
	CalculateStickForce()
	ClearAssign()
	ClearAxisAssign()
	ClearButtonAssign()
	ClearButtonPressLog()
	ClearStickAssign()
	ClearTriggerAssign()
	DeleteAxisAssign()
	DeleteButtonAssign()
	DeleteStickAssign()
	DeleteTriggerAssign()
	GetAssignedButtonNumber()
	GetAxis()
	GetButtonLastPressDuration()
	GetButtonLastReleaseDuration()
	GetButtonLongPress()
	GetButtonPress()
	GetButtonPressCountAsKeyRepeat()
	GetButtonPressDuration()
	GetButtonRelease()
	GetButtonReleaseDuration()
	GetButtonStatus()
	GetCameraDirection()
	GetDeviceType()
	GetMainPadIndex()
	GetStickAxis()
	GetStickDir()
	GetStickTilt()
	GetTrigger()
	RegisterAxisAssign()
	RegisterAxisAssignAsNoAxis()
	RegisterAxisReverse()
	RegisterButtonAssign()
	RegisterButtonAssignAsNoButton()
	RegisterStickAssign()
	RegisterStickAssignAsNoStick()
	RegisterStickAxisReverse()
	RegisterTriggerAssign()
	RegisterTriggerAssignAsNoTrigger()
	SetAxisMask()
	SetButtonMask()
	SetFullMask()
	SetMainPadIndex()
	SetPhysicalButtonMask()
	SetStickAxisMask()
	SetStickMask()
	SetTriggerMask()

	["_className"] = "Pad"
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "Pad"