_G["TppCheckPoint"]
	["_DoesBaseListInclude"] = loadstring()
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "TppCheckPoint"
	["DEBUG_Init"] = loadstring()
	["DeclareSVars"] = loadstring()
	["OnAllocate"] = loadstring()
	_DoesCheckPointListInclude()
	_RegisterCheckPoint()
	_SetEnable()
	DebugUpdate()
	Disable()
	Enable()
	FindNearestCheckPoint()
	GetCheckPointLocator()
	Init()
	IsEnable()
	Messages()
	OnMessage()
	OnReload()
	RegisterCheckPointList()
	Reset()
	SetCheckPointPosition()
	Update()
	UpdateAtCurrentPosition()