_G["TppDemo"] = {
	["_DoMessage"] = loadstring()
	["_scriptPath"] = "TppDemo"
	["CanUpdateMBDemo"] = loadstring()
	["CheckEventDemoDoor"] = loadstring()
	["ClearIgnoreNpcDisableOnDemoEnd"] = loadstring()
	["ClearPlayedMBEventDemoFlag"] = loadstring()
	["ClearReserveInTheBackGround"] = loadstring()
	["DeletePlayRequestInfo"] = loadstring()
	["DisableGameStatusOnPlayRequest"] = loadstring()
	["EnableGameStatus"] = loadstring()
	["EnableInGameFlagIfResereved"] = loadstring()
	["FadeOutOnSkip"] = loadstring()
	["GetDemoStartPlayerPosition"] = loadstring()
	["GetMBDemoName"] = loadstring()
	["IsBattleHangerDemo"] = loadstring()
	["IsPlayedMBEventDemo"] = loadstring()
	["IsQuestStart"] = loadstring()
	["IsSortieMBDemo"] = loadstring()
	["IsUseMBDemoStage"] = loadstring()
	["OnDemoSkip"] = loadstring()
	["OnDemoSkipAndBlockLoadEnd"] = loadstring()
	["OnEndGameCameraInterp"] = loadstring()
	["ReserveEnableInGameFlag"] = loadstring()
	["SetNextMBDemo"] = loadstring()
	["SetPlayerPause"] = loadstring()
	["SetPlayerWarp"] = loadstring()
	["SetStageBlockLoadPosition"] = loadstring()
	["UnsetPlayerPause"] = loadstring()
	["UnsetStageBlockLoadPosition"] = loadstring()
	["UpdateNuclearAbolitionFlag"] = loadstring()
	_OnDemoDisable()
	_OnDemoEnd()
	_OnDemoInit()
	_OnDemoInterrupt()
	_OnDemoPlay()
	_OnDemoSkip()
	_Play()
	AddDemo()
	AddFinishWaitRequestInfo()
	AddPlayReqeustInfo()
	CanFinishPlay()
	CanStartPlay()
	DisableGameStatusOnPlayStart()
	DoOnEndMessage()
	EnableNpc()
	EnableWaitBlockLoadOnDemoSkip()
	ExecuteBackGroundLoad()
	FinalizeOnDemoBlock()
	Init()
	IsNotPlayable()
	Messages()
	OnAllocate()
	OnDemoDisable()
	OnDemoEnd()
	OnDemoInterrupt()
	OnDemoPlay()
	OnMessage()
	OnReload()
	Play()
	PlayGetIntelDemo()
	PlayOnDemoBlock()
	PlayOpening()
	ProcessFinishWaitRequestInfo()
	ProcessPlayRequest()
	Register()
	ReserveInTheBackGround()
	SetDemoTransform()
	SpecifyIgnoreNpcDisable()
	Update()
	UpdateHappyBirthDayFlag()
	UpdateMBDemo()

	["FINISH_WAIT_START_FUNC"] = {
		["playerModelReloaded"] = loadstring()
		["waitTextureLoadOnDemoEnd"] = loadstring()
		["waitBlockLoadEndOnDemoSkip"] = loadstring()
	}
	["Y_REQUEST_START_CHECK_FUNC"] = { --broken name
		["gameCameraInterpedToDemo"] = loadstring()
		["missionStateCheck"] = loadstring()
		["playerActionAllowed"] = loadstring()
		["playerModelReloaded"] = loadstring()
		["playerMoveToPosition"] = loadstring()
		demoBlockLoaded()
		waitTextureLoadOnDemoPlay()
	}
	

	["MOVET_TO_POSITION_RESULT"] = {
		[1028433999] = "timeout"
		[3042441730] = "success"
		[2897250610] = "failure"
	}
	["PLAY_REQUEST_START_FUNC"] = {
		["demoBlockLoaded"] = loadstring()
		["missionStateCheck"] = loadstring()
		["playerActionAllowed"] = loadstring()
		["playerModelReloaded"] = loadstring()
		["playerMoveToPosition"] = loadstring()
		["waitTextureLoadOnDemoPlay"] = loadstring()
		gameCameraInterpedToDemo()
	}
	["FINISH_WAIT_CHECK_FUNC"] = {
		["playerModelReloaded"] = loadstring()
		["waitTextureLoadOnDemoEnd"] = loadstring()
		["waitBlockLoadEndOnDemoSkip"] = loadstring()
	}
	["mtbsPriorityFuncList"] = {
		["ArrivedMotherBaseFromDeathFactory"] = loadstring()
		["ArrivedMotherBaseLiquid"] = loadstring()
		["DdogGoWithMe"] = loadstring()
		["DetailsNuclearDevelop"] = loadstring()
		["EndingSacrificeOfNuclear"] = loadstring()
		["ForKeepNuclearElimination"] = loadstring()
		["GoToMotherBaseAfterQuietBattle"] = loadstring()
		["HappyBirthDayWithQuiet"] = loadstring()
		["NuclearEliminationCeremony"] = loadstring()
		["ParasiticWormCarrierKill"] = loadstring()
		["QuietReceivesPersecution"] = loadstring()
		["SacrificeOfNuclearElimination"] = loadstring()
		["SnakeHasBadSmell_001"] = loadstring()
		["TheGreatEscapeLiquid"] = loadstring()
		AnableDevBattleGear()
		AttackedFromOtherPlayer_KnowWhereFrom()
		AttackedFromOtherPlayer_UnknowWhereFrom()
		CodeTalkerSunBath()
		DdogComeToGet()
		DecisionHuey()
		EliLookSnake()
		EntrustDdog()
		HappyBirthDay()
		InterrogateQuiet()
		LiquidAndChildSoldier()
		LongTimeNoSee_DdogHighLikability()
		LongTimeNoSee_DdogLowLikability()
		LongTimeNoSee_DdogPup()
		LongTimeNoSee_DdogSuperHighLikability()
		LongTimeNoSee_DDSoldier()
		MoraleOfMBIsLow()
		OcelotIsPupilOfSnake()
		QuietHasFriendshipWithChild()
		QuietOnHeliInRain()
		QuietWishGoMission()
		SnakeHasBadSmell_000()
		SnakeHasBadSmell_WithoutQuiet()
	}
	["_scriptInstanceId"] = [[userdata]]
}