_G["TppHelicopter"]
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "TppHelicopter"
	["AdjustBuddyDropPoint"] = loadstring()
	["ForcePullOut"] = loadstring()
	["GetMissionStartHelicopterRoute"] = loadstring()
	["GetPassengerlist"] = loadstring()
	["GetSupportHeliGameObjectId"] = loadstring()
	["ResetMissionStartHelicopterRoute"] = loadstring()
	["SetNoSupportHelicopter"] = loadstring()
	["UnsetNoSupportHelicopter"] = loadstring()
	CallToLandingZone()
	ClearPassengerTable()
	ForceCallToLandingZone()
	GetEnemyColoringPack()
	GetLandingZoneExists()
	Init()
	IsInHelicopter()
	SetDefaultTakeOffTime()
	SetDisableLandingZone()
	SetEnableLandingZone()
	SetEnemyColoring()
	SetNewestPassengerTable()
	SetNoTakeOffTime()
	SetRouteToHelicopterOnStartMission()