_G["TppInterrogation"]
	["_OnMapUpdate"] = loadstring()
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "TppInterrogation"
	["DeclareSVars"] = loadstring()
	["InitUniqueInterrogation"] = loadstring()
	["ResetQuestTable"] = loadstring()
	_AddGene()
	_AssignInterrogation()
	_AssignInterrogationCollection()
	_OnInterrogation()
	_OnInterrogationEnd()
	_SelectInterrogation()
	AddGeneInter()
	AddHighInterrogation()
	AddQuestTable()
	Init()
	InitInterrogation()
	MakeFlagHigh()
	Messages()
	OnMessage()
	OnReload()
	QuestInterrogation()
	RemoveHighInterrogation()
	RemoveQuestHighIntTable()
	ResetFlagHigh()
	ResetFlagNormal()
	SetQuestHighIntTable()
	UniqueInterrogation()
	UniqueInterrogationWithVoice()