_G["TppLocation"]
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "TppLocation"
	["GetLocalMbStageClusterGrade"] = loadstring()
	["GetLocationName"] = loadstring()
	["GetMbStageClusterGrade"] = loadstring()
	["GetMbStageHelicopterRoute"] = loadstring()
	["IsAfghan"] = loadstring()
	["IsCyprus"] = loadstring()
	["IsMBQF"] = loadstring()
	["IsMiddleAfrica"] = loadstring()
	["IsMotherBase"] = loadstring()
	["MbFreeSpecialMissionStartSetting"] = loadstring()
	["ModifyMbsLayoutCode"] = loadstring()
	["OnActiveLargeBlock"] = loadstring()
	["OnActiveSmallBlock"] = loadstring()
	["RegistBaseAssetTable"] = loadstring()
	["RegistMissionAssetInitializeTable"] = loadstring()
	["SetBuddyBlock"] = loadstring()
	ActivateBlock()
	ApplyPlatformParamToMbStage()
	DEBUG_UseDebugMbParam()
	Init()
	Messages()
	OnMessage()
	OnReload()
	SetForceConstructDevelopCluster()