_G["TppMain"]
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "TppMain"
	["ClearStageBlockMessage"] = loadstring()
	["DisableBlackLoading"] = loadstring()
	["DisableGameStatus"] = loadstring()
	["DisableGameStatusOnGameOverMenu"] = loadstring()
	["DisablePause"] = loadstring()
	["DisablePlayerPad"] = loadstring()
	["EnableAllGameStatus"] = loadstring()
	["EnableBlackLoading"] = loadstring()
	["EnableGameStatus"] = loadstring()
	["EnableGameStatusForDemo"] = loadstring()
	["EnablePause"] = loadstring()
	["EnablePlayerPad"] = loadstring()
	["OnChangeSVars"] = loadstring()
	["OnEnterMissionPrepare"] = loadstring()
	["OnMissionCanStart"] = loadstring()
	["OnMissionStartSaving"] = loadstring()
	["OnTextureLoadingWaitStart"] = loadstring()
	["StageBlockCurrentPosition"] = loadstring()
	OnAllocate()
	OnInitialize()
	OnMessage()
	OnMissionGameStart()
	OnReload()
	OnTerminate()
	OnUpdate()
	ReservePlayerLoadingPosition()
	SetMessageFunction()
	SetUpdateFunction()
