_G["TppPaz"]
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "TppPaz"
	["DEMO_END_TYPE_DOWN"] = 2
	["DEMO_END_TYPE_NONE"] = 0
	["DEMO_END_TYPE_SIT"] = 1
	["GetItemInTableAtRandom"] = loadstring()
	["GetStartPosition"] = loadstring()
	["GetStartRotationY"] = loadstring()
	["Init"] = loadstring()
	["InitMusic"] = loadstring()
	["InitPlayer"] = loadstring()
	["InitUi"] = loadstring()
	["OnAllocate"] = loadstring()
	["OnPazSnakeIsMoving"] = loadstring()
	["SetDemoEndType"] = loadstring()
	["SetStartType"] = loadstring()
	["START_TYPE_DOWN"] = 2
	["START_TYPE_NO_PICTURE"] = 0
	["START_TYPE_PICTURE"] = 1
	["TermMusic"] = loadstring()
	["TermPlayer"] = loadstring()
	["TermUi"] = loadstring()
	ActiveMessages()
	GetDemoEndType()
	GetPazGameObjectId()
	GetPosition()
	GetRotationY()
	GetStartType()
	InactiveMessages()
	InitTimer()
	IsInTable()
	IsMonologuePhotoSpeech()
	IsReal()
	NeedsToWaitLeave()
	OnClock()
	OnDemoEnter()
	OnEnter()
	OnFinishTimer()
	OnIconOk()
	OnIconSwitchShown()
	OnLeave()
	OnMessage()
	OnMonologueEnd()
	OnPazHasAimedDefault()
	OnPazHideIcon()
	OnPazInAngle()
	OnPazOutAngle()
	OnPazPerceiveSnake()
	OnPazRelaxEndTiming()
	OnPazShowIcon()
	OnPazSnakeIsStopping()
	OnReload()
	OnSpecialActionEnd()
	PlayCameraAnimation()
	PlayPlayerMotion()
	SendCommandCallMonologue()
	SendCommandSpecialAction()
	UpdateIcon()
	Warp()