_G["TppScriptBlock"]
	["_scriptInstanceId"] = [[userdata]]
	["_scriptPath"] = "TppScriptBlock"
	["ClearSavedScriptBlockInfo"] = loadstring()
	["FindPackList"] = loadstring()
	["GetCurrentPackListName"] = loadstring()
	["SaveScriptBlockId"] = loadstring()
	["Unload"] = loadstring()
	ActivateScriptBlockState()
	DeactivateScriptBlockState()
	DEBUG_ClearPreloadRequest()
	DEBUG_PreloadRequest()
	DeclareSVars()
	FinalizeScriptBlockState()
	InitScriptBlockState()
	IsRequestActivate()
	Load()
	LoadDemoBlock()
	OnAllocate()
	PreloadRequestOnMissionStart()
	PreloadSettingOnMissionStart()
	RegisterCommonBlockPackList()
	ReloadScriptBlock()
	RequestActivate()
	RequestActivateByBlockId()
	ResolveSavedScriptBlockInfo()
	SetScriptBlockState()