TppSoldier2CommonBlockController
	CreateCommonMotionBlockGroup()
	IsBlockActive()
	IsBlockEmpty()
	IsReady()
	RegisterCommonMotionPackagePath()
	RequestToLoadCommonMotionBlock()
	RequestToUnloadCommonMotionBlock()
	SetPackagePathWithPrerequisites()